name:                hasktorch-tools
version:             0.2.0.7
github:              DaisukeBekki/hasktorch-tools
license:             LGPL
author:              Daisuke Bekki and BekkiLab
maintainer:          bekki@is.ocha.ac.jp
copyright:           Daisuke Bekki and BekkiLab
synopsis:            Haskell Tools for Deep Learning via libtorch
category:            Machine Learining
ghc-options:         -Wall
extra-source-files:
- README.md
- ChangeLog.md
description:         https://github.com/DaisukeBekki/hasktorch-tools#readme

dependencies:
# for hasktorch
- base >= 4.7 && < 5
- hasktorch >= 0.2
- libtorch-ffi 
- libtorch-ffi-helper
- codegen 
- async
- finite-typelits
- ghc-typelits-extra >= 0.3.1
- ghc-typelits-knownnat >= 0.7
- ghc-typelits-natnormalise >= 0.7
- ghc-typelits-extra
- ghc-typelits-knownnat
- ghc-typelits-natnormalise
- mtl
- safe-exceptions
- reflection
- singletons
- stm
- JuicyPixels
- vector
- bytestring
- safe-exceptions
- zlib >= 0.6
# for hasktorch-tools
- text >= 1.2
- filepath >= 1.4
- directory >= 1.3
- shelly >= 1.6
- nlp-tools >= 0.1.9
- cereal >= 0.5
- cereal-text >= 0.1
- aeson >= 1.0
- bytestring >= 0.10
- yaml >= 0.8.3
- json-stream >= 0.4

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  - MultiParamTypeClasses
  - RecordWildCards
  exposed-modules:
  - Torch.Control
  - Torch.Train
  - Torch.Layer.Linear
  - Torch.Layer.MLP
  - Torch.Layer.RNN
  - Torch.Layer.LSTM
  - Torch.Layer.SimpleLSTM
  - Torch.Layer.ProtoType.LSTM
  - Torch.Tensor.TensorFactories
  - Torch.Tensor.Initializers
  - Torch.Tensor.Util
#  - Torch.LangModel.Juman.Dict
#  - Torch.LangModel.Juman.Model
  - Torch.Config.EngEmbedRegConfig
  - Torch.Config.JumanLstmConfig
  
executables:
  # test:
  #   main:                Main.hs
  #   source-dirs:         app/test
  #   ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
  #   dependencies:
  #     - hasktorch-tools
  first-tensor:
    main:         Main.hs
    source-dirs:  app/first-tensor
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: hasktorch-tools
  xor-mlp:
    main:         Main.hs
    source-dirs:  app/xor-mlp
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: hasktorch-tools
  lstmSample:
    main:         Main.hs
    source-dirs:  app/lstmSample
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: hasktorch-tools
#  regression:
#    main:         Main.hs
#    source-dirs:  app/regression
#    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies: hasktorch-tools
#  seq-reg-train:
#    main:         seq-reg-train.hs
#    source-dirs:  app/seq-lbl
#    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies: hasktorch-tools
#  seq-preprocess:
#    main:         preprocess.hs
#    source-dirs:  app/seq-lbl
#    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies: hasktorch-tools
#  seq-class-train:
#    main:         seq-class-train.hs
#    source-dirs:  app/seq-lbl
#    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies: hasktorch-tools
#  eng-embed-reg-bow-train:
#    main:         train_bow.hs
#    source-dirs:  app/eng-embed-reg
#    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies: hasktorch-tools
#  eng-embed-reg-bow-eval:
#    main:         eval_bow.hs
#    source-dirs:  app/eng-embed-reg
#    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies: hasktorch-tools
#  eng-embed-reg-lstm-train:
#    main:         train_lstm.hs
#    source-dirs:  app/eng-embed-reg
#    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies: hasktorch-tools
#  juman-lstm-preprocess:
#    main:         preprocessing.hs
#    source-dirs:  app/juman-lstm-language-model
#    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies: hasktorch-tools
#  juman-lstm-train:
#    main:         train.hs
#    source-dirs:  app/juman-lstm-language-model
#    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies: hasktorch-tools
#  gpu-test:
#    main:         Main.hs
#    source-dirs:  app/gpu-test
#    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies: hasktorch-tools
#  getCovid19data:
#    main:                Main.hs
#    source-dirs:         app/covid19
#    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies:
##      - http-conduit >= 2.3
##      - req >= 3.1
#      - lens >= 0.4
#      - aeson >= 1.4
#      - aeson-lens >= 0.5
#      - bytestring
#  amazon-review:
#    main:                Main.hs
#    source-dirs:         app/amazon-review
#    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
#    dependencies:
#      - hasktorch-tools
#      - containers >= 0.6
tests:
  lstmTest:
    main:         Main.hs
    source-dirs:  test/lstmTest
    ghc-options:  [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: 
      - hasktorch-tools
      - HUnit >= 1.6.0