#resolver: lts-17.1
resolver: lts-18.28

flags: {}

extra-include-dirs:
  - ../../.local/lib/hasktorch/deps/libtorch/include
  - ../../.local/lib/hasktorch/deps/libtorch/include/torch/csrc/api/include
  - ../../.local/lib/hasktorch/deps/mklml/include

extra-lib-dirs:
  - ../../.local/lib/hasktorch/deps/libtorch/lib
  - ../../.local/lib/hasktorch/deps/mklml/lib

extra-deps:
  - ../../.local/lib/hasktorch/codegen
  - ../../.local/lib/hasktorch/libtorch-ffi
  - ../../.local/lib/hasktorch/libtorch-ffi-helper
  - ../../.local/lib/hasktorch/hasktorch
  - datasets-0.4.0@sha256:9bfd5b54c6c5e1e72384a890cf29bf85a02007e0a31c98753f7d225be3c7fa6a,4929
  - pipes-text-0.0.2.5@sha256:16cfd1927817a1c757b15c37ad95c67e819c28b1c4a6ce9757ab15276ec36ac7,3326
  - streaming-cassava-0.1.0.1@sha256:2d1dfeb09af62009e88311fe92f44d06dafb5cdd38879b437ea6adb3bc40acfe,1739
  - streaming-bytestring-0.1.7@sha256:5b53960c1c5f8352d46a4f1a604d04340a08dcf7ff27ca3ed31253e02c01fd03,2968
  - stm-2.5.0.0@sha256:c238075f9f0711cd6a78eab6001b3e218cdaa745d6377bf83cc21e58ceec2ea1,2100
  - require-0.4.10@sha256:41b096daaca0d6be49239add1149af9f34c84640d09a7ffa9b45c55f089b5dac,3759
  - git: https://github.com/mcwitt/tintin
    commit: cad1ab21e53a3c734e09143def4fe862ded9e67a
# hasktorch-tools
  - Chart-cairo-1.9.1
  - cairo-0.13.8.0
  - gtk2hs-buildtools-0.13.8.0
  - aeson-1.4.7.1
  - aeson-lens-0.5.0.0
  - json-stream-0.4.2.4
  - git: git@github.com:DaisukeBekki/nlp-tools.git
    commit: 0b6912850dbffd14ed16c3fa26a0773c877ba093


allow-newer: true
    
build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true
