resolver: lts-14.27

flags: {}

extra-include-dirs:
  - ../.local/lib/hasktorch/libtorch/include
  - ../.local/lib/hasktorch/libtorch/include/torch/csrc/api/include
  - ../.local/lib/hasktorch/mklml/include
extra-lib-dirs:
  - ../.local/lib/hasktorch/libtorch/lib
  - ../.local/lib/hasktorch/mklml/lib
extra-deps:
  - ../.local/lib/hasktorch/codegen
  - ../.local/lib/hasktorch/libtorch-ffi
  - ../.local/lib/hasktorch/libtorch-ffi-helper
  - ../.local/lib/hasktorch/hasktorch
#  - template-0.2.0.10@sha256:f822de4d34c45bc84b33a61bc112c15fedee6fa6dc414c62b10456395a868f85
  - inline-c-0.9.0.0   #@sha256:7b5aa24a265cb50fd71f1a2595506f5a7dec98edcf40b7fbe617193668a90f31,3249
  - inline-c-cpp-0.4.0.0
  - regex-tdfa-1.2.3.2 #@sha256:bec13812a56a904ff3510caa19fe1b3ce3939e303604b1bcb3162771c52311ba,6324
#  - regex-base-0.94.0.0@sha256:44aa95ca762294ffbb28cf0af9c567d93b5d2c56e4f38ce5385a257d899f968e,2253
# hasktorch
  - ghc-typelits-natnormalise-0.7
  - ghc-typelits-knownnat-0.7
  - ghc-typelits-extra-0.3.2
# examples/typed-transformer
  - git: git://github.com/hasktorch/pipes-text.git
    commit: 3dd3d9519306ea06f0c15ad71bdf57e1dfd0b747
# experimental/dataloader-cifar10
  - datasets-0.4.0 #@sha256:9bfd5b54c6c5e1e72384a890cf29bf85a02007e0a31c98753f7d225be3c7fa6a,4929
  - streaming-attoparsec-1.0.0.1 #@sha256:fe9b878072423d3f075534fe8af24722d9ded1a1129e9a6ed5b71c4a29681b39,1146
  - streaming-cassava-0.1.0.1 #@sha256:2d1dfeb09af62009e88311fe92f44d06dafb5cdd38879b437ea6adb3bc40acfe,1739
# hasktorch-tools
  - Chart-cairo-1.9.1
  - cairo-0.13.8.0
  - gtk2hs-buildtools-0.13.8.0
#  - req-3.1.0
  - aeson-1.4.7.1
  - aeson-lens-0.5.0.0
  - ../JSeM
  - ../juman-tools
  - git: git://github.com/creswick/chatter.git
    commit: a10cb59f5d70fd2a5def35a319ea254a2db3004d
  - cereal-0.5.7.0
  - fullstop-0.1.4
  - tokenize-0.3.0
  - regex-base-0.93.2

build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true
