resolver: lts-15.1

flags: {}

extra-include-dirs:
  - ../../.local/lib/hasktorch/pytorch/torch/include
  - ../../.local/lib/hasktorch/pytorch/torch/csrc/api/include
  - ../../.local/lib/hasktorch/mklml/include

extra-lib-dirs:
  - ../../.local/lib/hasktorch/pytorch/torch/lib
  - ../../.local/lib/hasktorch/mklml/lib

extra-deps:
  - ../../.local/lib/hasktorch/codegen
  - ../../.local/lib/hasktorch/libtorch-ffi
  - ../../.local/lib/hasktorch/libtorch-ffi-helper
  - ../../.local/lib/hasktorch/hasktorch
#  - template-0.2.0.10
  - inline-c-0.9.0.0
  - inline-c-cpp-0.4.0.0
# hasktorch
  - ghc-typelits-natnormalise-0.7
  - ghc-typelits-knownnat-0.7
  - ghc-typelits-extra-0.3.2
# examples/typed-transformer
  - git: git://github.com/hasktorch/pipes-text.git
    commit: 3dd3d9519306ea06f0c15ad71bdf57e1dfd0b747
# experimental/dataloader-cifar10
  - datasets-0.4.0 
  - streaming-attoparsec-1.0.0.1 
  - streaming-cassava-0.1.0.1 
# hasktorch-tools
  - Chart-cairo-1.9.1
  - cairo-0.13.8.0
  - gtk2hs-buildtools-0.13.8.0
  - aeson-1.4.7.1
  - aeson-lens-0.5.0.0
  - json-stream-0.4.2.4
  - git: git@github.com:DaisukeBekki/juman-tools.git
    commit: 68005951bf12d80ade4a94a22892c203c143b911

build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true
